/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Erc20 } from "./Erc20";
export type { Erc20Transfer } from "./Erc20Transfer";

export { Erc20__factory } from "./factories/Erc20__factory";
export { Erc20Transfer__factory } from "./factories/Erc20Transfer__factory";
